# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Pierre Robiglio
email: pierre.robiglio@gmail.com
description: Pierre Robiglio's personal page.

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# code highlighter theme
highlight_theme_light: github
highlight_theme_dark: native

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

twitter_username: pierrerobiglio

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: al-folio
blog_nav_title: blog
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_darkmode: true
enable_progressbar: true
enable_project_categories: true
enable_medium_zoom: true

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

bootstrap:
  version: "4.6.1"
  integrity:
    css: "sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY="
    js: "sha256-fgLAgv7fyCGopR/gBNq2iW3ZKIdqIcyshnUULC4vex8="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
mathjax:
  version: "3.2.0"
