project:
  type: website
  output-dir: docs

website:
  title: "Pierre Robiglio"
  navbar:
    left:
      - href: index.qmd
        text: About
      - CV.qmd
      - research.qmd
  announcement: 
    content: "This website is still under construction. Don’t hesitate to reach out for any information you need." 
    icon: info-circle
    dismissable: true
    type: primary
    position: below-navbar

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: Computer Modern, sans-serif;
    css: styles.css
    toc: true



