---
title: "Readings"
---

*This page is mostly for personal use, to keep track of the books I read and want to read.*

*These are mostly books in italian by italian authors.*

## On the list

**Una vita come tante** (Orig. *A Little Life*), Hanya Yanagihara, Sellerio, 2016

**La falce dei cieli**  (Orig. *The Lathe of Heaven*), Ursula K. Le Guin, Mondadori, 2025.

## 2025

**The Human Stain**, Philip Roth, Vintage, 2025 (*Houghton Mifflin, 2000*)

**Lo sbilico**, Alcide Pierantozzi, Einaudi, Einaudi, 2025.

**La felicità del lupo**, Paolo Cognetti, Einaudi, 2021.

**Poveri a noi**, Elvio Carrieri, Ventanas, 2024.

**Point Lenana**, Wu Ming 1 e Roberto Santachiara, Einaudi, 2016.

**Una questione privata**, Beppe Fenoglio, Einaudi, 2022 (*Garzanti, 1963*)

**Orso** (Orig. *Bear*), Marian Engel, La Nuova Frontiera, 2024.

**Incompletezza**, Deborah Gambetta, Ponte alle Grazie, 2024.

**Sostiene Pereira**, Antonio Tabucchi, Feltrinelli, 2019 (*Feltrinelli, 1995*)

**Portnoy** (Orig. *Portnoy's Complaint*), Philip Roth, Adelphi, 2025.

**Abel**, Alessandro Baricco, Feltrinelli, 2023.

**Il calcio del figlio**, Wu Ming 4, Alegre, 2025.

**Lessico familiare**, Natalia Ginzburg, Einaudi, 2014 (*Einaudi, 1963*).

**La breve stagione** (Orig. *Colchiques dans les prés*), Serge Quadruppani, Alegre, 2024. 

**La macchina del vento**, Wu Ming 1, Einaudi, 2019.

**Stirpe e vergogna**, Michela Marzano, Rizzoli, 2021.

**Gli uomini pesce**, Wu Ming 1, Einaudi, 2024.

**25**, Bernardo Zannoni, Sellerio, 2023.

**I miei stupidi intenti**, Bernardo Zannoni, Sellerio, 2021.

**La luna e i falò**, Cesare Pavese, La Stampa, 2008 (*Einaudi, 1950*).

**Cantalamappa. Tutte le storie**, Wu Ming, Electa Junior, 2024.

**La vera storia della banda Hood**, Wu Ming 4, Bompiani, 2024.

**La strangera**, Marta Aidala, Guanda, 2024.

**Il ragazzo selvatico. Quaderno di montagna**, Paolo Cognetti, Terre di Mezzo, 2013.

**Le venti giornate di Torino**, Giorgio de Maria, Frassinelli, 2017 (*Il formichiere, 1977*).

